# author: Polina Cherkasova <polina.c@live.com>

name: faui
description: >
  Authentication UI for Flutter. Uses Firebase auth as security provider.
  The library provides UI to register user, validate email, sign in, sign out,
  restore password, access data in Firestore.
version: 2.0.20
homepage: https://github.com/polina-c/flutter-auth-ui

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.14.6 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  uuid: ^2.0.1
  shared_preferences: ^0.5.6

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
